#!/usr/bin/env python

import sys
from shared_clipboard.clipboard import Clipboard

if len(sys.argv) == 1:
    data = sys.stdin.read()
elif len(sys.argv) == 2:
    data = open(sys.argv[1]).read()
else:
    print >>sys.stderr, ("Usage: %s [filename]" % sys.argv[0])
    sys.exit(1)

Clipboard().set(data)
